---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: how bluexp operational resiliency works, what is operational resiliency, bluexp 
summary: Die operative Ausfallsicherheit von BlueXP ist ein Service, mit dem Sie Alarme und Ereignisse analysieren können, um den Zustand, die Uptime und die Performance von Services und Lösungen aufrechtzuerhalten. Mithilfe des Service für die betriebliche Ausfallsicherheit und seiner automatisierten Vorschläge für die BETRIEBLICHE IT-Fehlerbehebung können Sie vorgeschlagene Korrekturmaßnahmen implementieren, bevor es zu einem Ausfall oder einem Ausfall kommt. 
---
= Erfahren Sie mehr über die operative Ausfallsicherheit von BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
Die betriebliche Ausfallsicherheit von BlueXP ist ein Service, der Ihnen bei der Analyse von Warnmeldungen und Ereignissen hilft, um den Zustand, die Uptime und die Performance von Services und Lösungen aufrechtzuerhalten. Mithilfe des Service für die betriebliche Ausfallsicherheit und seiner automatisierten Vorschläge zur Behebung DES IT-Betriebsrisikos können Sie vorgeschlagene Korrekturmaßnahmen implementieren, bevor es zu einem Ausfall oder einem Ausfall kommt.

Bei diesem BlueXP -Service werden die Korrekturmaßnahmen für NetApp ONTAP-Cluster auf Basis von Active IQ-Digital Advisor (auch als Digital Advisor bezeichnet) durchgeführt. Der Service erkennt Sicherheitslücken, z. B. Probleme mit der Firmware- und Softwarekonfiguration.



== Vorteile der betrieblichen Ausfallsicherheit von BlueXP

Die betriebliche Ausfallsicherheit von BlueXP bietet folgende Vorteile:

* Automatisierte Verfahren für Korrekturen im Cluster
* Übersichtsansicht des Dashboards mit dem Status der einzelnen Risikobehebungen
* Protokoll, mit dem Sie die verschiedenen durchgeführten Aktionen verfolgen können




== Was Sie mit der betrieblichen Ausfallsicherheit von BlueXP erreichen können

Mit dem Operational Resiliency Service können Sie folgende Ziele erreichen:

* Nutzen Sie automatisierte Workflows, mit denen Sie Risiken für Ihre Storage-Umgebung erkennen und Maßnahmen zur Minderung dieser Risiken ergreifen können.
* Prüfen Sie operative Empfehlungen, z. B. Probleme im Zusammenhang mit Sicherheitslücken, und handeln Sie entsprechend.




== Kosten

NetApp berechnet Ihnen keine Kosten für die Nutzung des Service.



== Unterstützte Umgebungen

Die betriebliche Ausfallsicherheit von BlueXP analysiert lokale NetApp ONTAP Cluster.
