---
sidebar: sidebar 
permalink: get-started/prerequisites.html 
keywords: what are bluexp operational resiliency requirements, economic efficiency prerequisites 
summary: 'Erste Schritte mit dem BlueXP Service für betriebliche Ausfallsicherheit: Prüfen Sie einfach, ob Ihre Umgebung, Ihr Netzwerkzugriff, Ihre Anmeldung und Ihren Webbrowser unterstützt.' 
---
= Voraussetzungen für die betriebliche Ausfallsicherheit von BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Prüfen Sie zunächst die Betriebsumgebung, die Anmeldung, den Netzwerkzugriff und den Webbrowser.

Um den Operational Resiliency-Service zu nutzen, sollten Sie sicherstellen, dass Ihre Umgebung alle Anforderungen erfüllt.

* Ihre Umgebung muss alle BlueXP Anforderungen erfüllen – einschließlich Anmeldung und Netzwerkzugriff über einen Webbrowser.
+
Siehe https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html["BlueXP Quick Start Guide"^] Und https://docs.netapp.com/us-en/bluexp-setup-admin/reference-networking-saas-console.html["BlueXP Netzwerkinformationen"^].

* Der Service erfordert, dass alle Cluster von Digital Advisor überwacht werden. Dies erfordert, dass AutoSupport auf dem Asset aktiviert ist. Siehe https://docs.netapp.com/us-en/active-iq/index.html["Digital Advisor Dokumentation"^].
* Sie müssen über die Zugangsdaten für die Cluster verfügen.
* Für automatische Problembehebung ist ein BlueXP Connector erforderlich. Es ist hilfreich, wenn der BlueXP Connector aktiviert und aktiviert ist und das ONTAP System erkannt wird, bevor Sie eine Wiederherstellung mithilfe der betrieblichen Ausfallsicherheit von BlueXP einleiten. Wenn der Connector nicht vorhanden ist, führt Sie der Service für betriebliche Ausfallsicherheit durch diese Prozesse. Wenn Sie stattdessen eine Ansible Datei optimieren, ist der BlueXP Connector nicht erforderlich.

