---
sidebar: sidebar 
permalink: get-started/prerequisites.html 
keywords: what are bluexp operational resiliency requirements, economic efficiency prerequisites 
summary: 'Erste Schritte mit dem BlueXP Service für betriebliche Ausfallsicherheit: Prüfen Sie einfach, ob Ihre Umgebung, Ihr Netzwerkzugriff, Ihre Anmeldung und Ihren Webbrowser unterstützt.' 
---
= Voraussetzungen für die betriebliche Ausfallsicherheit
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Prüfen Sie zunächst die Betriebsumgebung, die Anmeldung, den Netzwerkzugriff und den Webbrowser.

Um den Operational Resiliency-Service zu nutzen, sollten Sie sicherstellen, dass Ihre Umgebung alle Anforderungen erfüllt.

* Ihre Umgebung muss alle BlueXP Anforderungen erfüllen – einschließlich Anmeldung und Netzwerkzugriff über einen Webbrowser.
+
Siehe https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-standard-mode.html["BlueXP Quick Start Guide"^] Und https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-networking-saas-console.html["BlueXP Netzwerkinformationen"^].

* Für den Service müssen alle Cluster von Digital Advisor (ehemals Digital Advisor von Active IQ) überwacht werden. Siehe https://docs.netapp.com/us-en/active-iq/index.html["Digital Advisor Dokumentation"^].
* Sie müssen über die Zugangsdaten für die Cluster verfügen.
* Es ist zwar keine Voraussetzung, aber hilfreich, wenn der BlueXP Connector vorhanden und aktiviert ist und das ONTAP System erkannt wird. Falls nicht, führt der Service zur betrieblichen Ausfallsicherheit Sie durch diese Prozesse.

