---
sidebar: sidebar 
permalink: get-started/setup.html 
keywords: bluexp, operational resiliency, risk remediate 
summary: Anstatt Kapazitäten hinzuzufügen oder kalte Daten zu verschieben, können Sie derzeit keine Aktion erforderlich auswählen und Erinnerungen für die erneute Prüfung nach 30, 60 oder 90 Tagen festlegen. 
---
= Richten Sie den Operational Resiliency Service ein
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Der erste Schritt auf dem Weg zur Nutzung des Operational Resiliency-Service besteht darin, die Daten aus den Monitoring-Tools in Ihrer Umgebung verfügbar zu machen.

Die Einrichtung des Dienstes umfasst die folgenden Schritte:

* Prüfen link:../get-started/prerequisites.html["Voraussetzungen"] Und stellen Sie sicher, dass Ihre Umgebung bereit ist
* Optional können Sie vor Nutzung des Service einen Connector in BlueXP erstellen
* Optional können Sie den Cluster in BlueXP erkennen, bevor Sie den Service verwenden




== Connector in BlueXP erstellen

Ein BlueXP Connector verfügt über Zugangsdaten für NetApp ONTAP Machines, sodass der Service zur betrieblichen Ausfallsicherheit Sicherheitsrisiken erkennen und Korrekturmaßnahmen durchführen kann.

Sie können einen Connector direkt in BlueXP erstellen und diesen Connector im Service Operational Resiliency verwenden. Sie können auch den Prozess der Betrachtung des Clusters starten und in der Mitte dieses Prozesses den Connector bereitstellen.

Informationen zum Erstellen eines Connectors in BlueXP vor der Nutzung des Service finden Sie in der BlueXP Dokumentation, die in der Beschreibung beschrieben ist https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["So erstellen Sie einen Konnektor"^].



== Cluster in BlueXP entdecken

Im Rahmen der Einrichtung werden der Cluster-Name, die IP, der Benutzername und das Passwort in BlueXP ermittelt.

Anweisungen hierzu finden Sie in der BlueXP Dokumentation, in der es erläutert wird https://docs.netapp.com/us-en/cloud-manager-setup-admin/index.html["Identifikation des Clusters"^].
